<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MinGo.Messaging.Samples.SimpleMessageBroker</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Core\MinGo.Messaging.Core\MinGo.Messaging.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Hosting\MinGo.Messaging.Hosting\MinGo.Messaging.Hosting.csproj" />
    <ProjectReference Include="..\..\..\src\SimpleMessageBroker\MinGo.Messaging.SimpleMessageBroker\MinGo.Messaging.SimpleMessageBroker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
